---

name: CapesLocker
version: 1.2.1
main: Verre2OuiSki\CapesLocker\CapesLocker
api: 5.0.0
extensions: [gd]

author: Verre2OuiSki
description: Add your own capes to the server !
website: https://github.com/Verre2OuiSki